[package]
name = "orml-traits"
description = "Shared traits including `BasicCurrency`, `MultiCurrency`, `Auction` and more."
repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/traits"
license = "Apache-2.0"
version = "0.4.1-dev"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2021"

[dependencies]
scale-info = { version = "2.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
sp-runtime = { git = "https://github.com/arbprof/substrate", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }
sp-io = { git = "https://github.com/arbprof/substrate", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }
sp-std = { git = "https://github.com/arbprof/substrate", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }
num-traits = { version = "0.2.14", default-features = false }
impl-trait-for-tuples = "0.2.2"
frame-support = { git = "https://github.com/arbprof/substrate", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }
orml-utilities = { path = "../utilities", version = "0.4.1-dev", default-features = false }
xcm = { git = "https://github.com/arbprof/polkadot", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"num-traits/std",
	"frame-support/std",
	"orml-utilities/std",
	"xcm/std",
]
